### ISSUE TITLE
Red and Blue are switched hexxit

### ISSUE THREAD

**Issue by segault** [TechnicPack/TechnicLauncher#1274]
So Hexxit launches fine, but when i play the colors are wrong, i think red and blue might be switched
<img width="770" alt="Screen Shot 2022-01-03 at 2 58 58 PM" src="https://user-images.githubusercontent.com/83902095/147923367-2b636c24-9194-4dce-b68d-772d787e361b.png">
<img width="900" alt="Screen Shot 2022-01-03 at 2 59 30 PM" src="https://user-images.githubusercontent.com/83902095/147923376-b0bb3987-f45f-4911-92a9-001775512d24.png">
<img width="904" alt="Screen Shot 2022-01-03 at 3 00 14 PM" src="https://user-images.githubusercontent.com/83902095/147923380-5c9fc50f-dec5-4740-81cc-14f5737c082f.png">

**Comment by Pyker** [comment]
Are you on an M1 Mac?

**Comment by segault** [comment]
Yes, m1 macbook air with 16 gb RAM, if it helps

**Comment by CZG408** [comment]
Hi this is a known issue with M1 macs running older MC versions due to the way M1s process color. There is a texturepack that fixes the vanilla part: [Vanilla Textures](https://drive.google.com/file/d/10eH6zmJ6seH_bNVD0JJY2MXwCZ14NT4m/view?usp=drive_open)  or you can install a full pack that edits everything including the modded stuff such as BDCraft.
