### ISSUE TITLE
Transferring Worlds from Technic

### ISSUE THREAD

**Issue by Link10101** [TechnicPack/TechnicLauncher#151]
I just transferred my favourite world from the old technic pack to the new tekkit lite pack which is very similar. But the ic2_map.cfg file in my world is different then the IC2.cfg in the new tekkit lite config folder, so when I add the world none of my mod blocks appear. So I was wondering which file I should change? Here is a preview of the 2 files.
![Screen Shot 2013-03-13 at 1 31 45 PM](https://f.cloud.github.com/assets/3855998/255111/1bb4d842-8c04-11e2-8bf7-dca4bb4e834b.png)

**Comment by Dribble** [comment]
This is an uneducated guess to fixing your problem:
NOTE!: Save a backup before testing this idea!

From the looks of the IC2.cfg on the left to the ic2_map.cfg on the right, the contents look the same, just with varying values. I assume that because it's a preview of both files, the left-hand side preview can be scrolled down and should show similar contents to match the right-hand side preview.

Edit the values in the IC2.cfg (left) to match the ones found in ic2_map.cfg (right).
Easy way to do this is to copy/paste everything under:

#Fri Jan 25 08:28:40 EST 2013

-in the ic2_map.cfg to IC2.cfg and then do a Find/Replace (granted I have no clue how to do this in Mac) for "block." and change it to "I:"
From the preview you've shown, none of the contents have changed, just the values.

Maybe that will fix your issue, but please save a backup, I don't want you to lose stuff.

**Comment by Salynne** [comment]
Please consult our forums for issues with the modpacks themselves. This issue tracker is for the launcher itself.

http://forums.technicpack.net/threads/how-to-convert-tekkit-classic-world-to-tekkit-lite.34915/
