### ISSUE TITLE
Make directory for each build rather than modpack and allow directory management

### ISSUE THREAD

**Issue by luisantonioa** [TechnicPack/TechnicLauncher#26]

**Comment by rupertcow** [comment]
Just a suggestion why dont you add a drop down select box under your login name. This drop down box would select profiles such as creating your own. For example saving profiles of mod configurations so people could set up there mod configuration then save the name of the profile such as "Technic -Dungeons -Milleonaire" This could also make backups easier if they have named the profile. 

So people could have there Player skin model there then under the name button they could select the profile they have made such as "Technic +NEI Cheat". Players could simply select the profile they have and then they could click there name button and it would revert to that profile and Technic/Tekkit version ready to play.

I am very unsure how the backup is saved and reverts so this may be impossible to implement I would just think its better using profiles like backups instead of multiple directories.

Thanks for reading
