### ISSUE TITLE
List of Files in Modpacks should be checked before extraction.

### ISSUE THREAD

**Issue by Obbi89** [TechnicPack/TechnicLauncher#290]
Hey even though I do know that it's easier to inject malcious code via Minecraft itself 
there should be checks on the Modpacks/Mods before extraction.

Reason?
Well take this example: http://u5b.de/nations/mods/mods/cheat/cheat-1.zip (ignore the kiddy like filenames, it was just a test and we needed some filenames...)
On Windows machines this zip file extracts files to the users Desktop and changes his Solder config to only contain a certain mod.
You could even put files in the Startup folder or anywhere on Drive c:\ (as long as the user has permission to write files).
Thereof you should warn users, or skip extraction of zip files containing .. folders.
(Beware that you could even hide it within subfolders!)

I think it's a security issue that should be adressed.
Anyone else's thoughts on this?

Thanks.

**Comment by Salynne** [comment]
How does the zip extract to the desktop? It should only extract inside of the launcher folder.

I extracted it and it came out where I extracted it at, not on the desktop.

You can't put folders that navigate backwards in a zip can you? The best you can do is subfolders inside the launcher folder. Shouldn't have any effect on anything because the launcher is required to be installed in an empty folder. (Or your .technic folder)

**Comment by Obbi89** [comment]
Don't use a Software to test the archive. 
90% of tools is intelligent enough to remove trailing ..\ folders.
But last time I tested this on the Launchers internal unzipping tools it did not remove those.

**Comment by Obbi89** [comment]
And yes you can do backwards folders in zip.

**Comment by CannibalVox** [comment]
Hello, I've verified that the 1.6-compatible launcher has the appropriate security fixes for this issue.
