### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by digosdfj** [TechnicPack/TechnicLauncher#381]
Stack Trace: Exception: RuntimeException Message: Library net.minecraft:launchwrapper:1.8 not found. Trace: net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:153) net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99) net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55) org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

**Comment by devoirz** [comment]
I have this exact same problem, with the exact same error dialogue. First it doesn't even want to start with the download because of some dropbox issue, but then when I get it download, it crashes through half way, and shows this message, and then I need to restart the whole program, what is the problem?

**Comment by CannibalVox** [comment]
Fixed in Stable 373.
