### ISSUE TITLE
Stop wiping folders every launch!

### ISSUE THREAD

**Issue by ruifung** [TechnicPack/TechnicLauncher#419]
Everytime the launcher is restarted, it WIPES AND REINSTALLS the modpack. This causes issues as its wiping out all user defined settings like video settings and custom controls. This should not happen, it should only WIPE AND REINSTALL on reset or update. Not once every launch.

**Comment by abalabahaha** [comment]
Following latest beta steam, same issue. I'm annoyed at how every time I open any pack, all of my carefully configured settings are gone. Plus the jar resets, losing my hack client and shaders.

**Comment by ruifung** [comment]
Beta? It's been pushed to stable already.

**Comment by CannibalVox** [comment]
Which modpack, guys?  Come on, you both know how to report bugs better than this!

**Comment by delta534** [comment]
I can report this happening with never stop toasting, but not with big dig. It also happens if no changes are made to the modpack Here is a paste of the launcher log of just starting the launcher and starting NST. NST was already installed before the launch.

http://codepad.org/HM0I9v12 

I can get more data tomorrow if needed.

**Comment by CannibalVox** [comment]
Thank you delta- I've pushed build 383 to stable- it should fix this issue.
