### ISSUE TITLE
error damn

### ISSUE THREAD

**Issue by ferrazmatt** [TechnicPack/TechnicLauncher#836]
When I open launcher technic give this error http://pastebin.com/aS8r4jaz

**Comment by MyNickIsBetter** [comment]
There are many people having the same problem. I advise not to change anything on your computer, not even make updates or adjust settings on your computer. Those responsible for Technic Launcher will fix this error. Sorry if i'm spamming, because it is important to disclose that to most people possible

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
